/// Flutter icons CocktalCraft_AVB
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CocktalCraft_AVB
///      fonts:
///       - asset: fonts/CocktalCraft_AVB.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CocktalCraft_AVB {
  CocktalCraft_AVB._();

  static const _kFontFam = 'CocktalCraft_AVB';
  static const String? _kFontPkg = null;

  static const IconData glass =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocktail =
      IconData(0xf561, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
